spring.application.name=kafka-order-notification

server.port=8081

#Kafka
spring.kafka.bootstrap-servers=localhost:9092

# Reduce Kafka logs
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN

# Keep your application logs
logging.level.com.example.kafka=INFO