spring.application.name=kafka-multiple-consumers

server.port=8082

spring.kafka.bootstrap-servers=localhost:9092

logging.level.root=WARN
logging.level.org.apache.kafka=WARN
logging.level.org.springframework.kafka=WARN
logging.level.com.example.multiconsumer=INFO